id: system_settings_diagnostics_reports_disable
title: "Disable Sending Diagnostic and Usage Data to Apple"
discussion: |
  The ability to submit diagnostic data to Apple _MUST_ be disabled.
  
  The information system _MUST_ be configured to provide only essential capabilities. Disabling the submission of diagnostic and usage information will mitigate the risk of unwanted data being sent to Apple. 
check: " "
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - N/A
  cci: 
    - N/A
  800-53r5:
    - N/A
  800-53r4: 
    - N/A
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - N/A
  cis:
    benchmark: 
      - 2.2.1.12 (level 1)
      - 3.2.1.25 (level 1)
    controls v8:
      - 4.8
ios:
  - "16.0"
tags:
  - ios
  - cis_lvl1
  - cis_lvl2
  - cisv8
severity: "medium"
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowDiagnosticSubmission: false
