id: "system_settings_force_date_and_time_enable"
title: "Ensure Force automatic date and time is set to Enabled"
discussion: |
  Automatic date and time _MUST_ be enabled.
check: " "
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - N/A
  cci: 
    - N/A
  800-53r5:
    - AU-8
  800-53r4: 
    - N/A
  srg:
    - N/A
  disa_stig: 
    - N/A
  800-171r2:
    - N/A
  cis:
    benchmark:
      - 2.2.1.7 (level 1)
      - 3.2.1.17 (level 1)
    v8:
      - 8.4
iOS:
  - "16.0"
tags:
  - ios
  - cis_lvl1
  - cis_lvl2
  - cisv8
  - 800-53r5
severity: ""
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    forceAutomaticDateAndTime: true
