id: system_settings_personalized_advertising_disable
title: "Disable Personalized Advertising"
discussion: |
  Ad tracking and targeted ads _MUST_ be disabled.

  The information system _MUST_ be configured to provide only essential capabilities. Disabling ad tracking ensures that applications and advertisers are unable to track users' interests and deliver targeted advertisements.  
check: " "
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - N/A
  cci: 
    - N/A
  800-53r5:
    - N/A    
  800-53r4: 
    - N/A
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - N/A
  cis:
    benchmark:
      - 2.2.1.5 (level 1)
      - 3.2.1.11 (level 1)
    controls v8:
      - 4.8
iOS:
  - "16.0"
tags:
  - ios
  - cis_lvl1_byod
  - cis_lvl2_byod
  - cis_lvl1_enterprise
  - cis_lvl2_enterprise
  - cisv8
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowApplePersonalizedAdvertising: false